env:
  es6: true
  node: true
extends:
  - airbnb
  - prettier
plugins :
  - prettier
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier:
    - error
  no-useless-escape: 
    - off
